### ISSUE TITLE
ejemplos con bugs

### ISSUE THREAD

**Issue by ulisescrossa** [Fede112/DAS#1]
Hay errores en los ejemplos que aparecen dentro de las funciones, como en la linea 119 de funciones_das
    parametros['marcadores_color'] = ['r','g, 'b']
que falta el ' después de la g
Sería bueno que corran los ejemplos antes de ponerlos en las funciones así es más fácil el primer uso del script.

**Comment by Fede112** [comment]
Arreglados los ejemplos.
